<template>
	<!-- Reports Table -->
	<core-card
		slug="reports"
		:header-text="strings.reports"
		:toggles="false"
		no-slide
	>
		<template #tooltip>
			{{ strings.reportsTooltip }}
		</template>

		<core-wp-table
			ref="table"
			:columns="tableColumns"
			:rows="reports"
			:loading="loading || regeneratingUuid !== null"
			:totals="totals"
			show-pagination
			show-bulk-actions
			show-search
			:bulk-options="bulkOptions"
			:additional-filters="additionalFilters"
			:selected-filters="selectedFilters"
			@paginate="processPagination"
			@search="processSearch"
			@process-bulk-action="processBulkAction"
			@process-additional-filters="processAdditionalFilters"
			@sort-column="processSort"
		>
			<template #keyword="{ row }">
				<strong>
					<a
						href="#"
						@click.prevent="viewReport(row.uuid)"
					>
						{{ row.keyword }}
					</a>
				</strong>
				<div class="row-actions">
					<span>
						<a
							href="#"
							class="view"
							@click.prevent="viewReport(row.uuid)"
						>
							<span>{{ strings.viewReport }}</span>
						</a> |
					</span>

					<span>
						<a
							href="#"
							class="regenerate"
							@click.prevent="regenerateReport(row)"
							:class="{ 'regenerating': regeneratingUuid === row.uuid }"
						>
							<span>{{ strings.regenerate }}</span>
						</a> |
					</span>

					<span class="trash">
						<a
							href="#"
							class="submitdelete"
							@click.prevent="maybeDeleteReport(row.uuid)"
						>
							<span>{{ strings.delete }}</span>
						</a>
					</span>
				</div>
			</template>

			<template #status="{ row }">
				<span class="status-badge" :class="`status-${row.status}`">
					{{ row.status }}
				</span>
			</template>

			<template #brandsMentioned="{ row }">
				{{ row.brandsMentioned || '-' }}
			</template>

			<template #created="{ row }">
				<span :title="row.created ? new Date(row.created).toLocaleString() : '-'">
					{{ row.created ? dateFormat(new Date(row.created), 'M j, Y') : '-' }}
				</span>
			</template>

			<template #actions="{ row }">
				<base-button
					type="gray"
					class="btn-toggle-row allow-click"
					@click="viewReport(row.uuid)"
				>
					<svg-caret width="20"/>
				</base-button>
			</template>

		</core-wp-table>

		<core-modal
			:show="showDeleteModal"
			no-header
			@close="showDeleteModal = false"
		>
			<template #body>
				<div class="aioseo-modal-body">
					<button
						class="close"
						@click.stop="showDeleteModal = false"
					>
						<svg-close @click="showDeleteModal = false" />
					</button>

					<h3>{{ areYouSureDeleteMessage }}</h3>

					<div class="reset-description" v-html="strings.actionCannotBeUndone" />

					<base-button
						type="blue"
						size="medium"
						@click="processDelete"
						:loading="deletingUuid !== null || loading"
					>
						{{ yesDeleteMessage }}
					</base-button>

					<base-button
						type="gray"
						size="medium"
						@click="showDeleteModal = false"
					>
						{{ strings.noChangedMind }}
					</base-button>
				</div>
			</template>
		</core-modal>
	</core-card>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useRouter } from 'vue-router'

import http from '@/vue/utils/http'
import links from '@/vue/utils/links'
import dateFormat from '@/vue/utils/dateFormat'

import CoreCard from '@/vue/components/common/core/Card'
import CoreModal from '@/vue/components/common/core/modal/Index'
import CoreWpTable from '@/vue/components/common/core/wp/Table'
import SvgClose from '@/vue/components/common/svg/Close'
import SvgCaret from '@/vue/components/common/svg/Caret'
import BaseButton from '@/vue/components/common/base/Button'

import { __, _n } from '@/vue/plugins/translations'

const td = import.meta.env.VITE_TEXTDOMAIN

const router = useRouter()

// Reactive data
const reports      = ref([])
const loading      = ref(false)
const pageNumber   = ref(1)
const itemsPerPage = ref(10)
const searchTerm   = ref('')
const orderBy      = ref('created')
const orderDir     = ref('desc')
const statusFilter = ref('all')
const totals       = ref({
	total    : 0,
	pages    : 1,
	per_page : 10
})
const deletingUuid = ref(null)
const showDeleteModal = ref(false)
const shouldDeleteUuid = ref(null)
const regeneratingUuid = ref(null)

// Strings
const strings = {
	reports              : __('Reports', td),
	reportsTooltip       : __('View and manage your keyword ranking reports generated by AI-powered analysis.', td),
	filterByStatus       : __('Filter by Status', td),
	allStatuses          : __('All Statuses', td),
	pending              : __('Pending', td),
	processing           : __('Processing', td),
	completed            : __('Completed', td),
	failed               : __('Failed', td),
	viewReport           : __('View Report', td),
	regenerate           : __('Regenerate', td),
	delete               : __('Delete', td),
	actionCannotBeUndone : __('This action cannot be undone.', td),
	noChangedMind        : __('No, I changed my mind', td)
}

// Bulk options
const bulkOptions = [
	{ label: strings.delete, value: 'delete' }
]

// Additional filters
const additionalFilters = [
	{
		name    : 'status',
		label   : strings.filterByStatus,
		options : [
			{ value: 'all', label: strings.allStatuses },
			{ value: 'pending', label: strings.pending },
			{ value: 'processing', label: strings.processing },
			{ value: 'completed', label: strings.completed },
			{ value: 'failed', label: strings.failed }
		]
	}
]

// Selected filters
const selectedFilters = computed(() => ({
	status : statusFilter.value
}))

// Table columns
const tableColumns = computed(() => [
	{
		slug     : 'keyword',
		label    : __('Keyword', td),
		sortable : true,
		sortDir  : 'keyword' === orderBy.value ? orderDir.value : 'asc',
		sorted   : 'keyword' === orderBy.value,
		width    : '40%'
	},
	{
		slug     : 'status',
		label    : __('Status', td),
		sortable : true,
		sortDir  : 'status' === orderBy.value ? orderDir.value : 'asc',
		sorted   : 'status' === orderBy.value
	},
	{
		slug     : 'brandsMentioned',
		label    : __('Brands', td),
		sortable : true,
		sortDir  : 'brandsMentioned' === orderBy.value ? orderDir.value : 'asc',
		sorted   : 'brandsMentioned' === orderBy.value
	},
	{
		slug     : 'created',
		label    : __('Created', td),
		sortable : true,
		sortDir  : 'created' === orderBy.value ? orderDir.value : 'desc',
		sorted   : 'created' === orderBy.value
	},
	{
		slug     : 'actions',
		label    : '',
		sortable : false,
		width    : '50px'
	}
])

// Methods
const formatReports = (reports) => {
	return reports.map(report => ({
		id              : report.uuid || '',
		uuid            : report.uuid || '',
		keyword         : report.keyword || '-',
		status          : report.status || 'pending',
		brandsMentioned : report.brands_mentioned || null,
		created         : report.created_at || new Date().toISOString()
	}))
}

const fetchReports = async () => {
	loading.value = true

	try {
		// Calculate offset from page number.
		const offset = 1 === pageNumber.value ? 0 : (pageNumber.value - 1) * itemsPerPage.value

		// Build query parameters.
		const queryParams = {}
		if (orderBy.value) {
			queryParams.orderBy = orderBy.value
		}
		if (orderDir.value) {
			queryParams.orderDir = orderDir.value
		}
		if (itemsPerPage.value) {
			queryParams.limit = itemsPerPage.value
		}
		if (null !== offset) {
			queryParams.offset = offset
		}
		if (searchTerm.value) {
			queryParams.searchTerm = searchTerm.value
		}
		if (statusFilter.value && 'all' !== statusFilter.value) {
			queryParams.status = statusFilter.value
		}

		let url = links.restUrl('ai/insights/reports')
		const queryString = new URLSearchParams(queryParams).toString()
		if (queryString) {
			url += '?' + queryString
		}

		const response = await http.get(url)
			.then(res => res.body)

		if (response.success && response.data?.reports) {
			reports.value = formatReports(response.data.reports)

			totals.value = {
				total    : response.data.total,
				pages    : Math.ceil(response.data.total / itemsPerPage.value),
				per_page : itemsPerPage.value
			}
		}
	} catch (error) {
		console.error('Error fetching reports:', error)
	} finally {
		loading.value = false
	}
}

const viewReport = (uuid) => {
	router.push({ name: 'keyword-reports', params: { uuid } })
}

const regenerateReport = async (row) => {
	if (!row || !row.uuid || regeneratingUuid.value === row.uuid) {
		return
	}

	regeneratingUuid.value = row.uuid

	try {
		const response = await http.post(links.restUrl(`ai/insights/reports/${row.uuid}/regenerate`))
			.then(res => res.body)

		if (response.success && response.data?.uuid) {
			router.push({ name: 'keyword-reports', params: { uuid: response.data.uuid } })
		} else {
			console.error('Failed to regenerate report:', response)
			regeneratingUuid.value = null
		}
	} catch (error) {
		console.error('Error regenerating report:', error)
		regeneratingUuid.value = null
	}
}

const maybeDeleteReport = (uuid) => {
	if (!uuid) {
		return
	}

	shouldDeleteUuid.value = uuid
	showDeleteModal.value = true
}

const deleteCount = computed(() => {
	return Array.isArray(shouldDeleteUuid.value) ? shouldDeleteUuid.value.length : 1
})

const areYouSureDeleteMessage = computed(() => {
	return _n(
		'Are you sure you want to delete this report?',
		'Are you sure you want to delete these reports?',
		deleteCount.value,
		td
	)
})

const yesDeleteMessage = computed(() => {
	return _n(
		'Yes, I want to delete this report',
		'Yes, I want to delete these reports',
		deleteCount.value,
		td
	)
})

const processDelete = async () => {
	const uuids = Array.isArray(shouldDeleteUuid.value) ? shouldDeleteUuid.value : [ shouldDeleteUuid.value ]

	if (!uuids.length) {
		return
	}

	// Single delete
	if (1 === uuids.length) {
		const uuid = uuids[0]
		if (deletingUuid.value === uuid) {
			return
		}

		deletingUuid.value = uuid

		try {
			const response = await http.delete(links.restUrl(`ai/insights/reports/${uuid}`))
				.then(res => res.body)

			if (response.success) {
				// Refresh reports
				fetchReports()
				showDeleteModal.value = false
				shouldDeleteUuid.value = null
			} else {
				console.error('Failed to delete report:', response)
			}
		} catch (error) {
			console.error('Error deleting report:', error)
		} finally {
			deletingUuid.value = null
		}
	} else {
		// Bulk delete
		await processDeleteBulkReports()
	}
}

const processPagination = (page) => {
	pageNumber.value = page
	fetchReports()
}

const processSearch = (term) => {
	searchTerm.value = term
	pageNumber.value = 1
	fetchReports()
}

const processSort = (column) => {
	// Toggle order direction if clicking the same column, otherwise set to ascending.
	if (column.slug === orderBy.value) {
		orderDir.value = 'asc' === orderDir.value ? 'desc' : 'asc'
	} else {
		orderBy.value = column.slug
		orderDir.value = column.sortDir || 'asc'
	}
	pageNumber.value = 1
	fetchReports()
}

const processAdditionalFilters = (data) => {
	const filters = data.filters || data
	statusFilter.value = filters.status || 'all'
	pageNumber.value = 1
	fetchReports()
}

const processBulkAction = async (data) => {
	const { action, selectedRows } = data

	if ('delete' === action && selectedRows && selectedRows.length) {
		shouldDeleteUuid.value = selectedRows
		showDeleteModal.value = true
	}
}

const processDeleteBulkReports = async () => {
	const uuids = Array.isArray(shouldDeleteUuid.value) ? shouldDeleteUuid.value : [ shouldDeleteUuid.value ]
	if (!uuids.length) {
		return
	}

	loading.value = true

	try {
		// Delete all selected reports
		const deletePromises = uuids.map(uuid =>
			http.delete(links.restUrl(`ai/insights/reports/${uuid}`))
				.then(res => res.body)
		)

		const responses = await Promise.all(deletePromises)
		const allSuccess = responses.every(response => response.success)

		if (allSuccess) {
			// Refresh reports
			await fetchReports()
			showDeleteModal.value = false
			shouldDeleteUuid.value = null
		} else {
			console.error('Some reports failed to delete:', responses)
		}
	} catch (error) {
		console.error('Error deleting reports:', error)
	} finally {
		loading.value = false
	}
}

// Lifecycle
onMounted(() => {
	fetchReports()
})
</script>

<style lang="scss" scoped>
.status-badge {
	display: inline-block;
	padding: 2px 6px;
	border-radius: 2px;
	font-size: $font-sm;
	font-weight: $font-bold;
	text-transform: capitalize;
	border: 1px solid;

	&.status-processing,
	&.status-pending {
		color: $orange;
		border-color: $orange;
	}

	&.status-failed {
		color: $red;
		border-color: $red;
	}

	&.status-completed {
		color: $green;
		border-color: $green;
	}
}

.aioseo-modal-body {
	padding: 20px !important;
	display: flex;
	align-items: center;
	justify-content: center;
	flex-direction: column;
	position: relative;

	h3 {
		font-size: 20px;
		margin-bottom: 16px;
	}

	.reset-description {
		font-size: 16px;
		color: $black;
		margin-bottom: 16px;
		text-align: center;
		max-width: 515px;
	}

	button.close {
		position: absolute;
		right: 11px;
		top: 11px;
		width: 24px;
		height: 24px;
		background-color: $white;
		border: none;
		display: flex;
		align-items: center;
		cursor: pointer;

		svg {
			cursor: pointer;
			width: 14px;
			height: 14px;
		}
	}

	.aioseo-button:not(.close) {
		margin-top: 16px;
	}
}

.btn-toggle-row {
	display: flex;
	height: 26px;
	margin: 0 auto;
	padding: 0;
	width: 30px;

	svg {
		transform: rotate(-90deg);
		transition: transform 0.3s;
	}

	&.active {
		svg {
			transform: rotate(0);
		}
	}
}
</style>