<?php
/**
 * Generate wp-salts.php with fresh authentication keys and salts.
 *
 * WordPress normally sends people to api.wordpress.org/secret-key/1.1/salt/,
 * but that host is not reachable from every environment, and it is not needed:
 * the salts only have to be long, unique and unpredictable, which random_bytes
 * provides locally.
 *
 * The generated file is git-ignored. Generate it once per install; running it
 * again invalidates every cookie and logs all users out.
 *
 * Usage:
 *   php tools/db/generate-salts.php          # writes ./wp-salts.php
 *   php tools/db/generate-salts.php --force  # overwrite an existing file
 *   php tools/db/generate-salts.php --env    # print export lines instead
 */

$keys = array(
	'AUTH_KEY',
	'SECURE_AUTH_KEY',
	'LOGGED_IN_KEY',
	'NONCE_KEY',
	'AUTH_SALT',
	'SECURE_AUTH_SALT',
	'LOGGED_IN_SALT',
	'NONCE_SALT',
);

$argv  = $argv ?? array();
$force = in_array( '--force', $argv, true );
$as_env = in_array( '--env', $argv, true );

/**
 * Returns a 64-character random string drawn from the printable set
 * WordPress itself uses for salts.
 *
 * random_bytes() is used rather than rand()/uniqid(): these values guard
 * session cookies and nonces, so a predictable generator would undo the point
 * of having them.
 *
 * @return string
 */
function wpk_random_salt() {
	$alphabet = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
		. '!@#$%^&*()-_ []{}<>~`+=,.;:/?|';
	$max      = strlen( $alphabet ) - 1;
	$salt     = '';

	for ( $i = 0; $i < 64; $i++ ) {
		$salt .= $alphabet[ random_int( 0, $max ) ];
	}

	return $salt;
}

$values = array();
foreach ( $keys as $key ) {
	$values[ $key ] = wpk_random_salt();
}

if ( $as_env ) {
	foreach ( $values as $key => $value ) {
		// escapeshellarg keeps quotes and backticks in the alphabet from
		// breaking out of the assignment when the output is eval'd or sourced.
		echo 'export ' . $key . '=' . escapeshellarg( $value ) . "\n";
	}
	exit( 0 );
}

$target = dirname( __DIR__, 2 ) . '/wp-salts.php';

if ( file_exists( $target ) && ! $force ) {
	fwrite( STDERR, "refusing to overwrite {$target}\n" );
	fwrite( STDERR, "pass --force if you mean to; it logs every user out.\n" );
	exit( 1 );
}

$php = "<?php\n"
	. "/**\n"
	. " * Authentication unique keys and salts.\n"
	. " *\n"
	. " * Generated by tools/db/generate-salts.php. Not committed: this file is\n"
	. " * listed in .gitignore. Regenerating it logs every user out.\n"
	. " */\n\n";

foreach ( $values as $key => $value ) {
	$php .= sprintf( "define( %-20s %s );\n", "'{$key}',", var_export( $value, true ) );
}

if ( false === file_put_contents( $target, $php ) ) {
	fwrite( STDERR, "could not write {$target}\n" );
	exit( 1 );
}

chmod( $target, 0640 );

echo "wrote {$target}\n";
echo "8 keys generated; the file is git-ignored and readable by owner and group only.\n";
