<template>
	<div class="aioseo-tab-content aioseo-post-general">
		<core-settings-row
			v-if="allowed('aioseo_page_general_settings')"
			class="snippet-preview-row"
			no-right-max-width
		>
			<template #name>
				<div>
					<span class="snippet-preview-row-label">{{ strings.serpPreview }}</span>

					<core-tooltip
						offset="0,0"
						placement="bottom"
					>
						<svg-circle-question-mark/>

						<template #tooltip>
							{{ strings.serpPreviewDocumentation }}
						</template>
					</core-tooltip>
				</div>

				<base-radio-toggle
					v-if="'metabox' === screenContext || 'modal' === props.parentComponentContext"
					:modelValue="postEditorStore.currentPost.generalMobilePrev"
					@update:modelValue="isMobilePreviewEv"
					name="previewGeneralIsMobile"
					class="circle"
					:options="[
						{ label: 'desktop', value: false, activeClass: 'dark', slot: 'desktop' },
						{ label: 'mobile', value: true, slot: 'mobile' }
					]"
				>
					<template #desktop>
						<svg-desktop />
					</template>
					<template #mobile>
						<svg-mobile />
					</template>
				</base-radio-toggle>
			</template>

			<template #content>
				<core-google-search-preview
					:focus-keyphrase="postEditorStore.currentPost?.keyphrases?.focus?.keyphrase ?? ''"
					:device="'sidebar' === screenContext && 'metabox' === props.parentComponentContext ? 'mobile' : (postEditorStore.currentPost.generalMobilePrev ? 'mobile' : 'desktop')"
					:url="tagsStore.liveTags.permalink"
					:title="parseTags(postEditorStore.currentPost.title || postEditorStore.currentPost.tags.title || '#post_title #separator_sa #site_title')"
					:description="parseTags(postEditorStore.currentPost.description || postEditorStore.currentPost.tags.description || '#post_content')"
					:rich-results="seoPreviewStore.richResults"
				/>

				<base-button
					v-if="'sidebar' === screenContext && 'modal' !== props.parentComponentContext"
					class="edit-snippet gray small"
					@click="editSnippetEv"
				>
					<svg-pencil />
					{{ strings.editSnippet }}
				</base-button>
			</template>
		</core-settings-row>

		<core-settings-row
			id="aioseo-post-settings-post-title-row"
			class="snippet-title-row"
			v-if="('metabox' === screenContext || 'modal' === props.parentComponentContext) && allowed('aioseo_page_general_settings')"
			:name="title"
			:key="titleKey"
		>
			<template #content>
				<core-html-tags-editor
					:line-numbers="false"
					single
					@counter="count => titleCount = count.length"
					v-model="postEditorStore.currentPost.title"
					:tags-context="`${postEditorStore.currentPost.postType || postEditorStore.currentPost.termType}Title`"
					:defaultMenuOrientation="'modal' === props.parentComponentContext ? 'top' : 'bottom'"
					:default-tags="getDefaultTags('title')"
				>
					<template #tags-description>
						{{ strings.clickToAddTitle }}
					</template>

					<template v-if="
						allowed('aioseo_page_ai_content_settings') &&
						!postEditorStore.currentPost.isWooCommercePageWithoutSchema &&
						postEditorStore.currentPost.postType &&
						!['attachment', 'web-story'].includes(postEditorStore.currentPost.postType)" #append-button
					>
						<ai-generator
							:feature="aiFeatures.metaTitle"
						/>
					</template>
				</core-html-tags-editor>

				<div
					class="max-recommended-count"
					v-html="maxRecommendedCount(titleCount, 60)"
				/>
			</template>
		</core-settings-row>

		<core-settings-row
			id="aioseo-post-settings-meta-description-row"
			class="snippet-description-row"
			v-if="('metabox' === screenContext || 'modal' === props.parentComponentContext) && allowed('aioseo_page_general_settings')"
			:name="strings.metaDescription"
			:key="descriptionKey"
		>
			<template #content>
				<core-alert
					v-if="showAutogenerateDescriptionsAlert"
					type="yellow"
				>
					<span v-html="strings.autogenerateDescriptionsAlert" />
				</core-alert>

				<core-html-tags-editor
					:line-numbers="false"
					description
					@counter="count => descriptionCount = count.length"
					v-model="postEditorStore.currentPost.description"
					:tags-context="`${postEditorStore.currentPost.postType || postEditorStore.currentPost.termType}Description`"
					:defaultMenuOrientation="'modal' === props.parentComponentContext ? 'top' : 'bottom'"
					:default-tags="getDefaultTags('description')"
				>
					<template #tags-description>
						{{ strings.clickToAddDescription }}
					</template>

					<template v-if="
						allowed('aioseo_page_ai_content_settings') &&
						!postEditorStore.currentPost.isWooCommercePageWithoutSchema &&
						postEditorStore.currentPost.postType &&
						!['attachment', 'web-story'].includes(postEditorStore.currentPost.postType)" #append-button
					>
						<ai-generator
							:feature="aiFeatures.metaDescription"
						/>
					</template>
				</core-html-tags-editor>

				<div
					class="max-recommended-count"
					v-html="maxRecommendedCount(descriptionCount, 160)"
				/>
			</template>
		</core-settings-row>

		<core-settings-row
			v-if="
				'modal' !== props.parentComponentContext &&
				'metabox' === screenContext &&
				'post' === postEditorStore.currentPost.context &&
				!['attachment', 'web-story'].includes(postEditorStore.currentPost.postType) &&
				!isPageBuilderEditor() &&
				allowed('aioseo_page_general_settings')
			"
			id="aioseo-post-settings-cornerstone-content-row"
			class="cornerstone-content-row"
		>
			<template #name>
				{{ strings.cornerstoneContent }}

				<core-pro-badge
					v-if="licenseStore.isUnlicensed"
				/>
			</template>

			<template #content>
				<cornerstone-content
					@changeTab="newTab => $emit('changeTab', newTab)"
				/>
			</template>
		</core-settings-row>

		<template v-if="displayTruSeoMetaboxCard">
			<div v-if="optionsStore.options.searchAppearance.advanced.useKeywords && optionsStore.options.searchAppearance.advanced.keywordsLooking">
				<core-alert
					class="meta-keywords-alert"
					type="blue"
					show-close
					@close-alert="hideKeywordsLooking"
				>
					{{ strings.lookingForMetaKeywords }}

					<a
						href="#"
						@click.prevent="$emit('changeTab', 'advanced')"
					>
						{{ strings.goToAdvancedTab }}
					</a>

					<a
						class="no-underline"
						href="#"
						@click.prevent="$emit('changeTab', 'advanced')"
					>
						→
					</a>
				</core-alert>
			</div>

			<core-settings-row
				id="aioseo-post-settings-snippet-focus-keyphrase-row"
				class="snippet-focus-keyphrase-row"
				align
			>
				<template #name>
					<span>{{ strings.focusKeyphrase }}</span>

					<core-tooltip :offset="'25px,0'">
						<svg-circle-question-mark />

						<template #tooltip>
							<div v-html="strings.keyphraseDocumentation" />
						</template>
					</core-tooltip>
				</template>

				<template #content>
					<focus-keyphrase />
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.additionalKeyphrases"
				class="snippet-additional-keyphrases-row"
			>
				<template #content>
					<additional-keyphrases />
				</template>
			</core-settings-row>
		</template>

		<core-settings-row
			v-if="displayTruSeoMetaboxCard && postEditorStore.currentPost.page_analysis"
			:name="strings.pageAnalysis"
			class="snippet-page-analysis-row"
			align
		>
			<template #content>
				<page-analysis />
			</template>
		</core-settings-row>

		<core-sidebar-card
			v-if="'sidebar' === screenContext && !isPageBuilderEditor() && 'modal' !== props.parentComponentContext && allowed('aioseo_page_general_settings')"
			class="card-cornerstone-content"
			slug="cornerstoneContent"
			:header-text="strings.cornerstoneContent"
		>
			<cornerstone-content
				@changeTab="newTab => $emit('changeTab', newTab)"
			/>
		</core-sidebar-card>

		<core-sidebar-card
			v-if="displayTruSeoSidebarKeyphraseCard"
			slug="focus"
			:focusScore="focusKeyphraseScore"
			class="card-focus-keyphrase"
		>
			<template #header>
				<span>{{ strings.focusKeyphrase }}</span>

				<core-tooltip :offset="'0,0'">
					<svg-circle-question-mark />

					<template #tooltip>
						<div v-html="strings.keyphraseDocumentation" />
					</template>
				</core-tooltip>
			</template>

			<focus-keyphrase />
		</core-sidebar-card>

		<core-sidebar-card
			v-if="displayTruSeoSidebarKeyphraseCard"
			slug="additional"
			:header-text="strings.additionalKeyphrases"
			class="card-additional-keyphrase"
		>
			<additional-keyphrases />
		</core-sidebar-card>

		<core-sidebar-card
			v-if="displayTruSeoSidebarAnalysisCard"
			slug="basicseo"
			:header-text="strings.basicSeo"
			:trueSeoScore="postEditorStore.currentPost.page_analysis.analysis.basic.errors"
			class="card-basic-seo"
		>
			<metabox-analysis-detail :analysisItems="postEditorStore.currentPost.page_analysis.analysis.basic" />
		</core-sidebar-card>

		<core-sidebar-card
			v-if="displayTruSeoSidebarAnalysisCard"
			slug="title"
			:header-text="strings.title"
			:trueSeoScore="postEditorStore.currentPost.page_analysis.analysis.title.errors"
			class="card-title-seo"
		>
			<metabox-analysis-detail :analysisItems="postEditorStore.currentPost.page_analysis.analysis.title" />
		</core-sidebar-card>

		<core-sidebar-card
			v-if="displayTruSeoSidebarAnalysisCard"
			slug="readability"
			:header-text="strings.readability"
			:trueSeoScore="postEditorStore.currentPost.page_analysis.analysis.readability.errors"
			class="card-readability-seo"
		>
			<metabox-analysis-detail :analysisItems="postEditorStore.currentPost.page_analysis.analysis.readability" />
		</core-sidebar-card>
	</div>
</template>

<script setup>
import { ref, computed, watch, onMounted, onBeforeUnmount, getCurrentInstance } from 'vue'

import {
	useLicenseStore,
	useOptionsStore,
	usePostEditorStore,
	useRootStore,
	useSeoPreviewStore,
	useSettingsStore,
	useTagsStore,
	useTruSeoHighlighterStore
} from '@/vue/stores'

import { GLOBAL_STRINGS } from '@/vue/plugins/constants'
import { __, sprintf } from '@/vue/plugins/translations'
import { allowed } from '@/vue/utils/AIOSEO_VERSION'
import { merge } from 'lodash-es'
import { useMaxCounts } from '@/vue/composables/MaxCounts'
import { useTags } from '@/vue/composables/Tags'
import { useTruSeoHighlighter } from '@/vue/composables/TruSeoHighlighter'
import { useTruSeoScore } from '@/vue/composables/TruSeoScore'
import { debounce } from '@/vue/utils/debounce'
import { isPageBuilderEditor } from '@/vue/utils/context'
import { truSeoShouldAnalyze } from '@/vue/plugins/tru-seo/components/helpers'
import { aiFeatures } from './partials/ai-content/utils'

import links from '@/vue/utils/links'

import AdditionalKeyphrases from './partials/general/AdditionalKeyphrases'
import AiGenerator from './partials/general/ai/Generator'
import BaseRadioToggle from '@/vue/components/common/base/RadioToggle'
import CoreAlert from '@/vue/components/common/core/alert/Index'
import CoreGoogleSearchPreview from '@/vue/components/common/core/GoogleSearchPreview'
import CoreHtmlTagsEditor from '@/vue/components/common/core/HtmlTagsEditor'
import CoreSettingsRow from '@/vue/components/common/core/SettingsRow'
import CoreSidebarCard from '@/vue/components/common/core/SidebarCard'
import CoreTooltip from '@/vue/components/common/core/Tooltip'
import CoreProBadge from '@/vue/components/common/core/ProBadge'
import FocusKeyphrase from './partials/general/FocusKeyphrase'
import MetaboxAnalysisDetail from './partials/general/MetaboxAnalysisDetail'
import PageAnalysis from './partials/general/PageAnalysis'
import CornerstoneContent from './partials/general/CornerstoneContent'
import SvgCircleQuestionMark from '@/vue/components/common/svg/circle/QuestionMark'
import SvgDesktop from '@/vue/components/common/svg/Desktop'
import SvgMobile from '@/vue/components/common/svg/Mobile'
import SvgPencil from '@/vue/components/common/svg/Pencil'

defineEmits([ 'changeTab' ])

const td = import.meta.env.VITE_TEXTDOMAIN

const props = defineProps({
	disabled : {
		type : Boolean,
		default () {
			return false
		}
	},
	parentComponentContext : String
})

const licenseStore           = useLicenseStore()
const optionsStore           = useOptionsStore()
const postEditorStore        = usePostEditorStore()
const rootStore              = useRootStore()
const seoPreviewStore        = useSeoPreviewStore()
const settingsStore          = useSettingsStore()
const tagsStore              = useTagsStore()
const truSeoHighlighterStore = useTruSeoHighlighterStore()

const titleCount        = ref(0)
const descriptionCount  = ref(0)
const selectedKeyphrase = ref(0)
const editSnippet       = ref(false)
const titleKey          = ref('title' + 0)
const descriptionKey    = ref('description' + 0)

const { parseTags } = useTags({ separator: undefined })
const { maxRecommendedCount } = useMaxCounts()
const { watchHighlightSentences } = useTruSeoHighlighter()
const {
	runAnalysis,
	strings : composableStrings
} = useTruSeoScore()

const strings = merge(composableStrings, {
	pageName                      : __('General', td),
	serpPreview                   : __('SERP Preview', td),
	serpPreviewDocumentation      : __('SERP: Search Engine Results Page preview. Your site\'s potential appearance in Google search results. Final display may vary, but this preview closely resembles it.', td),
	editSnippet                   : __('Edit Snippet', td),
	clickToAddTitle               : __('Click on the tags below to insert variables into your title.', td),
	metaDescription               : __('Meta Description', td),
	clickToAddDescription         : __('Click on the tags below to insert variables into your meta description.', td),
	cornerstoneContent            : __('Cornerstone Content', td),
	focusKeyphrase                : __('Focus Keyword', td),
	additionalKeyphrases          : __('Additional Keywords', td),
	pageAnalysis                  : __('Page Analysis', td),
	basicSeo                      : __('Basic SEO', td),
	title                         : __('Title', td),
	readability                   : __('Readability', td),
	lookingForMetaKeywords        : __('Looking for meta keywords?', td),
	goToAdvancedTab               : __('Go to the Advanced tab to add/edit meta keywords', td),
	autogenerateDescriptionsAlert : sprintf(
		// Translators: 1 - The plugin short name ("AIOSEO"), 2 - A link to "Search Appearance > Advanced".
		__('Warning: You have disabled Autogenerate Descriptions and are using the default description format. %1$s will not output a description unless you enter a custom one. You can enable Autogenerate Descriptions under %2$s.', td),
		import.meta.env.VITE_SHORT_NAME,
		links.getPlainLink(
			__('Search Appearance > Advanced', td),
			rootStore.aioseo.urls.aio.searchAppearance + '#/advanced'
		)
	),
	keyphraseDocumentation : sprintf(
		// Translators: 1 - "Learn more link".
		__('Not sure what keywords are used for? Check out our documentation for more information. %1$s', td),
		links.getDocLink(GLOBAL_STRINGS.learnMore, 'useKeyphrasesTooltip', true)
	)
})

const screenContext = computed(() => {
	return getCurrentInstance().root.data.screenContext
})

const title = computed(() => {
	return sprintf(
		// Translators: 1 - The type of page (Post, Page, Category, Tag, etc.).
		__('%1$s Title', td),
		postEditorStore.currentPost.type
	)
})

const displayTruSeoMetaboxCard = computed(() => {
	return truSeoShouldAnalyze() && 'metabox' === screenContext.value && 'post' === postEditorStore.currentPost.context && 'modal' !== props.parentComponentContext && allowed('aioseo_page_analysis') && !isForum.value
})

const displayTruSeoSidebarKeyphraseCard = computed(() => {
	return truSeoShouldAnalyze() && 'sidebar' === screenContext.value && 'modal' !== props.parentComponentContext && allowed('aioseo_page_analysis') && !isForum.value
})

const displayTruSeoSidebarAnalysisCard = computed(() => {
	return truSeoShouldAnalyze() && 'sidebar' === screenContext.value && postEditorStore.currentPost.page_analysis && 'modal' !== props.parentComponentContext && allowed('aioseo_page_analysis') && !isForum.value
})

const isForum = computed(() => {
	return rootStore.aioseo.data.isBBPressActive &&
		(
			'forum' === postEditorStore.currentPost.postType ||
			'topic' === postEditorStore.currentPost.postType ||
			'reply' === postEditorStore.currentPost.postType
		)
})

const focusKeyphraseScore = computed(() => {
	if (!postEditorStore.currentPost.keyphrases.focus.keyphrase) {
		return null
	}

	return postEditorStore.currentPost.keyphrases.focus.score
})

const showAutogenerateDescriptionsAlert = computed(() => {
	if (!optionsStore.internalOptions.internal.deprecatedOptions.includes('autogenerateDescriptions')) {
		return false
	}

	const defaultDescription = 'post' === postEditorStore.currentPost.context
		? optionsStore.dynamicOptions.searchAppearance.postTypes[postEditorStore.currentPost.postType].metaDescription
		: optionsStore.dynamicOptions.searchAppearance.taxonomies[postEditorStore.currentPost.termType].metaDescription

	return defaultDescription === postEditorStore.currentPost.description && !optionsStore.options.deprecated.searchAppearance.advanced.autogenerateDescriptions
})

const hideKeywordsLooking = () => {
	optionsStore.options.searchAppearance.advanced.keywordsLooking = false
	optionsStore.saveChanges()
}

const isMobilePreviewEv = (ev) => {
	postEditorStore.changeGeneralPreview(ev)
}

const editSnippetEv = () => {
	editSnippet.value = !editSnippet.value
	settingsStore.changeTabSettings({ setting: 'modal', value: 'general' })
	postEditorStore.currentPost.modalOpen = true
}

const getDefaultTags = (location) => {
	switch (location) {
		case 'title':
			return 'post' === postEditorStore.currentPost.context
				? [
					'post_title',
					'separator_sa',
					'site_title'
				]
				: [
					'taxonomy_title',
					'separator_sa',
					'site_title'
				]
		case 'description':
			return 'post' === postEditorStore.currentPost.context
				? (
					'attachment' === postEditorStore.currentPost.postType
						? [
							'attachment_caption',
							'separator_sa',
							'site_title'
						]
						: 'product' === postEditorStore.currentPost.postType
							? [
								'post_excerpt',
								'post_content'
							]
							: [
								'post_excerpt',
								'post_content',
								'separator_sa'
							]
				)
				: [
					'taxonomy_title',
					'separator_sa',
					'taxonomy_description'
				]
	}
}

watch(() => postEditorStore.currentPost.title, () => {
	debounce(() => { runAnalysis({ postId: postEditorStore.currentPost.id }) }, 750)
})

watch(() => postEditorStore.currentPost.description, () => {
	debounce(() => runAnalysis({ postId: postEditorStore.currentPost.id }), 750)
})

watch(() => truSeoHighlighterStore.highlightSentences, (value, oldValue) => {
	debounce(() => watchHighlightSentences(value, oldValue))
})

onMounted(() => {
	if ('post' === postEditorStore.currentPost.context && !postEditorStore.currentPost.keyphrases.length) {
		selectedKeyphrase.value = -1
	}

	window.aioseoBus.$on('updateTitleKey', () => {
		titleKey.value = 'title' + Math.random(0, 999)
	})

	window.aioseoBus.$on('updateDescriptionKey', () => {
		descriptionKey.value = 'description' + Math.random(0, 999)
	})
})

onBeforeUnmount(() => {
	window.aioseoBus.$off('updateTitleKey')
	window.aioseoBus.$off('updateDescriptionKey')
})
</script>
<style lang="scss">
.aioseo-post-general {
	.aioseo-tooltip {
		line-height: normal;
		vertical-align: middle;

		:has(.aioseo-circle-question-mark) {
			display: inline-flex;
		}
	}

	svg.aioseo-circle-question-mark {
		width: 17px;
		height: 17px;
		color: $placeholder-color;
	}

	svg.aioseo-pencil {
		width: 12px;
		height: 12px;
		color: $black2;
	}

	.edit-snippet,
	.add-keyphrase {
		margin-top: 12px;
		border: 1px solid $gray;

		svg {
			margin-right: 11px;
		}
	}

	.disabled-button {
		margin-top: 12px;
		border: 1px solid #dcdde1;
		color: #8c8f9a;
		background-color: #f3f4f5;
		cursor: default;
		height: 40px;
		font-size: 14px;
		padding: 0 12px;
		flex-shrink: 0;
		line-height: 1;
		display: inline-flex;
		align-items: center;
		justify-content: center;
		font-weight: 600;
		border-radius: 4px;
		appearance: none;
		-webkit-appearance: none;
		transition: background-color .2s ease;
		position: relative;
		overflow: hidden;
		text-decoration: none;
		white-space: nowrap;

		svg {
			margin-right: 11px;
		}
	}

	.aioseo-keyphrase-tag {
		display: inline-block;
		margin-right: 10px;
		margin-bottom: 4px;
		border-radius: 3px;
		font-size: 14px;
		font-weight: $font-bold;

		&.selected {
			position: relative;

			&:before,
			&:after {
				content: '';
				position: absolute;
				display: block;
				z-index: 10;
				bottom: -15px;
				border-style: solid;
			}

			&:before {
				left: calc(50% - 12px);
				border-width: 0 10px 10px 10px;
				border-color: transparent transparent $blue transparent;
			}

			&:after {
				left: calc(50% - 10px);
				border-width: 0 9px 8px 8px;
				border-color: transparent transparent #fff transparent;
			}
		}

		.aioseo-add-keyphrase-tag {
			display: block;
			padding: 9px 10px;
			border: 1px solid $background;
			border-radius: 3px;
			background: $background;

			&.hidden {
				opacity: 0;
				height: 0;
				padding: 0
			}
		}

		.keyphrase-name {
			cursor: pointer;
		}

		.keyphrase-edit {
			opacity: 0;
			margin: 0 8px;
			cursor: pointer;

			svg {
				&.aioseo-pencil {
					width: 12px;
					height: 12px;
					color: $placeholder-color;
				}
			}
		}

		.keyphrase-score {
			cursor: pointer;

			&.score-green {
				color: $green
			}

			&.score-orange {
				color: $orange
			}

			&.score-red {
				color: $red
			}
		}

		.aioseo-edit-keyphrase-tag {
			position: relative;

			> input {
				color: $black;
				line-height: 1.5;
				width: 100%;
				padding: 8px 10px;
				border: 1px solid $border;
				border-radius: 3px;
			}

			.keyphrase-delete {
				position: absolute;
				top: 2px;
				right: 10px;
				width: 16px;
				height: 16px;
				display: block;
				cursor: pointer;

				&:hover {
					color: $red;
				}
			}
		}

		&:hover {
			.keyphrase-edit {
				opacity: 1;
			}
		}
	}

	.aioseo-analysis-detail {
		margin: 16px 0;

		&:last-child {
			margin-bottom: 0;
		}

		+ .aioseo-tooltip {
			margin-left: 0;

			.add-keyphrase {
				margin-top: 4px;
			}
		}
	}

	.analysis-wrapper {
		border-top: 1px solid $border;
	}

	.analysis-loading {
		position: relative;
		margin-top: 16px;
		margin-bottom: 16px;
	}

	.meta-keywords-alert {
		margin-bottom: 20px;
	}

	.snippet-description-row {
		.aioseo-modal-content & {
			border: none;
			margin-bottom: 0 !important;
			padding-bottom: 0 !important;
		}
	}

	.snippet-preview-row {
		.snippet-preview-row-label {
			vertical-align: middle;
		}

		.aioseo-google-search-preview {
			border: 1px solid $input-border;
			border-radius: 3px;
			padding: 10px;
			max-width: 610px;

			&--mobile {
				max-width: 375px;
			}
		}

		.settings-name .name {
			align-items: start;
			flex-direction: column;
			gap: 12px;
			white-space: nowrap;

			.aioseo-modal-content & {
				align-items: center;
				display: grid;
				grid-template-columns: auto 1fr;
				justify-items: end;
			}

			.aioseo-radio-toggle {
				gap: 10px;
			}
		}

		.edit-post-sidebar &,
		.editor-sidebar & {
			padding-bottom: 0 !important;
			border-bottom: none;
		}
	}

	.cornerstone-content-row {
		.cornerstone-content-panel {
			display: flex;
			flex-flow: column;

			p {
				order: 2;
			}
		}
	}

	.aioseo-alert {
		margin-bottom: 5px;

		&.inline-upsell {
			margin-top: 10px;
		}
	}

	.popper {
		max-width: 260px !important;
	}
}

.edit-post-sidebar,
.editor-sidebar {
	.aioseo-button.edit-snippet {
		display: inline-flex;
	}

	.snippet-focus-keyphrases-row {
		border-bottom: none;
		margin-bottom: 0 !important;
	}

	.card-focus-keyphrase,
	.card-additional-keyphrase,
	.card-basic-seo,
	.card-title-seo,
	.card-readability-seo,
	.card-cornerstone-content {
		margin: 0 -1rem;
		box-shadow: none;
		border: none;
		border-top: 1px solid $border;

		.header {
			padding: 1rem;
			border-bottom: none;
			font-size: 14px;
			font-weight: $font-bold;
		}

		.content {
			padding: 16px;
			font-size: 14px;
			border-top: 1px solid $border;
		}

		.aioseo-analysis-detail:last-of-type {
			margin-bottom: 0;

			.title {
				margin-bottom: 0;
			}
		}
	}

	.card-focus-keyphrase {
		.aioseo-analysis-detail {
			margin: 16px 0 !important;

			&:empty {
				margin: 16px;
			}
		}

		.add-keyphrase {
			width: 100%;
			font-size: 14px;
		}
	}

	.card-focus-keyphrase,
	.card-additional-keyphrase {
		.aioseo-analysis-detail {
			margin: 0 0 16px !important;
		}

		.add-keyphrase {
			width: 100%;
		}
	}

	.card-readability-seo {
		border-bottom: 1px solid $border;

		.aioseo-toggle {
			margin-bottom: 14px;
		}
	}

	.aioseo-keyphrase-tag {
		display: block;
		margin-right: 0;
		margin-bottom: 16px;

		&:after {
			content: none !important;
		}

		&.selected {
			&:before,
			&:after {
				content: none;
			}
		}

		.aioseo-add-keyphrase-tag {
			display: flex;
			width: 100%;
			align-items: center;

			.keyphrase-score {
				flex: 1;
				text-align: right
			}
		}
	}

	.card-basic-seo,
	.card-title-seo,
	.card-readability-seo {
		.aioseo-analysis-detail {
			margin-top: 0;
		}
	}

	.analysis-wrapper {
		border-top: none;
	}
}

.aioseo-modal-content {
	.aioseo-settings-row {
		--aioseo-gutter: 10px;
		row-gap: 12px;

		.settings-name .name {
			margin: 0;
		}
	}

	> .aioseo-settings-row {
		border: none;
		margin-bottom: 0!important;
	}

	.snippet-title-row,
	.snippet-description-row {
		position: relative;
		display: block;

		.settings-name {
			margin-bottom: 8px;
		}

		.aioseo-description {
			display: none;
		}

		.add-tags {
			.aioseo-add-template-tag {
				@media screen and (max-width: 520px) {
					display: none;
				}
			}
		}
	}

	.snippet-title-row {
		margin-top: 12px;
	}

	.snippet-pillar-row {
		display: none;
	}

	.component-wrapper {
		.aioseo-tabs .var-tab {
			&:not(.var-tab--active) {
				min-width: 72px!important;
				margin: 0 !important;
			}

			&:hover {
				background-color: #e2e3e6;
			}

			&:before {
				border-radius: 100%!important;
				display: none;
			}

			.tab-label {
				display: inline!important;
			}
		}
	}
}
</style>